.TH man 1 "01 Jan 2025" "checkpw 1.1.0" "checkpw man page"
.SH NAME
checkpw \- checks the validity of a users password on a UNIX/PAM-based system.
.SH SYNOPSIS
checkpw [OPTION]...
.SH DESCRIPTION
checkpw is a program that checks the validity of a users password on a UNIX/PAM-based system.
.SH OPTIONS
The options which apply to the checkpw command are:

  -u <username>  Set username.
  -p <password>  Set password.
  -v             Enable verbose mode.
  -V             Print program version.
  -h             Show this help.

checkpw runs in an interactive mode when no username and/or password are set. A missing username and/or password will then be asked for program execution.

.SH SEE ALSO
pam(3), pam_authenticate(3), PAM(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Johannes Findeisen (you@hanez.org)
