.TH man 1 "01 Jun 2025" "chkpw 1.2.0" "chkpw man page"
.SH NAME
chkpw \- checks the validity of a users password on a UNIX/PAM-based system.
.SH SYNOPSIS
chkpw [OPTION]...
.SH DESCRIPTION
chkpw is a program that checks the validity of a users password on a UNIX/PAM-based system.
.SH OPTIONS
The options which apply to the chkpw command are:

  -u <username>  Set username.
  -p <password>  Set password.
  -v             Enable verbose mode.
  -V             Print program version.
  -h             Show this help.

chkpw runs in an interactive mode when no username and/or password are set. A missing username and/or password will then be asked for program execution.

.SH SEE ALSO
pam(3), pam_authenticate(3), PAM(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Johannes Findeisen (you@hanez.org)
