.TH checkpw 1 "June 2025" "chkpwd 1.3.0" "chkpwd man page"
.SH NAME
chkpwd \- checks the validity of a users password on a UNIX/PAM-based system.
.SH SYNOPSIS
chkpwd [OPTION]...
.SH DESCRIPTION
chkpwd is a program that checks the validity of a users password on a UNIX/PAM-based system.
.SH OPTIONS
The options which apply to the chkpwd command are:

  -u <username>  Set username.
  -p <password>  Set password.
  -v             Enable verbose mode.
  -V             Print program version.
  -h             Show this help.

chkpwd runs in an interactive mode when no username and/or password are set. A missing username and/or password will then be asked for program execution.

.SH SEE ALSO
pam(3), pam_authenticate(3), PAM(8), pam_unix(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Johannes Findeisen (you@hanez.org)
